"""Generate docker/duckdb-ui/views.yaml from dbt target/manifest.json.

Source of truth: dbt external mart models (models/marts/).
매트 모델을 추가·삭제할 때 views.yaml 을 손으로 고칠 필요 없이 `make dbt-build` 한 번으로 동기화된다.

dbt manifest 의 external 모델 location 형식:
  - direnv 없을 때 (기본값): ../data/marts/x.parquet  (dbt/ 기준 상대경로)
  - QUANT_DATA_DIR 설정 시:  /abs/path/data/marts/x.parquet  (절대경로)
두 경우 모두 Docker DATA_DIR(=/data) 기준 상대경로(marts/x.parquet)로 변환한다.
"""
import json
import os
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "dbt" / "target" / "manifest.json"
OUT = ROOT / "docker" / "duckdb-ui" / "views.yaml"

# direnv 로 QUANT_DATA_DIR 이 설정된 경우 절대경로가 manifest 에 들어간다.
QUANT_DATA_DIR = os.environ.get("QUANT_DATA_DIR")
# 기본값(direnv 없음): dbt/ 기준 ../data/ 접두어를 제거.
_REL_PREFIX = re.compile(r"^\.\./data/")


def _to_data_rel(location: str) -> str:
    """manifest location → Docker DATA_DIR 기준 상대경로."""
    loc = Path(location)
    if loc.is_absolute() and QUANT_DATA_DIR:
        return str(loc.relative_to(QUANT_DATA_DIR))
    return _REL_PREFIX.sub("", location)


def main() -> None:
    if not MANIFEST.exists():
        print(f"[error] manifest 없음: {MANIFEST}\n  → make dbt-build 먼저 실행", file=sys.stderr)
        sys.exit(1)

    manifest = json.loads(MANIFEST.read_text())

    tables: dict[str, str] = {}
    for node in sorted(manifest.get("nodes", {}).values(), key=lambda n: n["name"]):
        if node.get("config", {}).get("materialized") != "external":
            continue
        name = node["name"]
        location: str = node.get("config", {}).get("location", "")
        tables[name] = _to_data_rel(location)

    header = (
        "# AUTO-GENERATED by scripts/gen_duckdb_views.py — do not edit by hand.\n"
        "# Source of truth: dbt/models/marts/ (external parquet models).\n"
        "# Regenerate: make dbt-build\n"
    )
    body = yaml.dump({"schemas": {"main": tables}}, default_flow_style=False, allow_unicode=True)
    OUT.write_text(header + body)

    print(f"[gen_duckdb_views] {OUT.relative_to(ROOT)} — {len(tables)} views:")
    for name, path in tables.items():
        print(f"  {name:30s} → {path}")


if __name__ == "__main__":
    main()
